interop with tjgm
Hyperledger-TWGC/ccs-gm pull request #28
Opened 2021-03-20 02:19 UTC by triplewz

1.支持解析tjgm生成的pem
2.sm2密文顺序已按最新标准修改

2021-05-07 13:58 UTC, SamYuan1990 requested changes

2021-05-07 13:58 UTC, SamYuan1990 commented on utils/keys_test.go
> +	pk,err := PEMtoPublicKey(pubpem,[]byte("123"))
suggestion adding testing for null password as edge case.

2021-05-07 13:58 UTC, SamYuan1990 commented on x509/pem_decrypt.go
> +	iter := 2048
please add comments here for const value 2048?

2021-05-07 13:59 UTC, SamYuan1990 commented
@triplewz , sorry for update late, please see my comments above.

2021-05-07 13:59 UTC, SamYuan1990 commented
@czdsdo , please help review impl for pkcs#8

2021-05-08 02:26 UTC, triplewz commented on x509/pem_decrypt.go
> +	iter := 2048
这一部分是参考tj的代码， 麻烦请tj的再确认下吧

2021-05-08 03:09 UTC, triplewz commented on utils/keys_test.go
> +	pk,err := PEMtoPublicKey(pubpem,[]byte("123"))
TestPEM2Key 里已经包含了非加密形式的测试

2021-05-09 12:16 UTC, SamYuan1990 commented on utils/keys_test.go
> +	pk,err := PEMtoPublicKey(pubpem,[]byte("123"))
ok

2021-05-09 12:19 UTC, SamYuan1990 commented
我先merge了， @davidkhala 麻烦看下互操作库效果吧。
CC： @czdsdo , @HanDaXia 
如果二位发现这个pr有什么问题，我们在看回滚或者fix up

2021-05-09 12:19 UTC, SamYuan1990 approved these changes

2021-05-09 12:20 UTC, merged

2021-05-09 14:07 UTC, davidkhala commented
@sam
今天在GM-interopt上bump ccs-gm 到latest，发现依然无法修复CI，不过还没跟以前的错误信息作对比

比如：https://dev.azure.com/Hyperledger/TWGC/_build/results?buildId=34354&view=logs&jobId=3e228f63-e175-5c9e-ed25-3fbb93cc3131&j=3e228f63-e175-5c9e-ed25-3fbb93cc3131&t=c7f33201-64f9-5467-8357-40bcaab38bb7