fix bigs for arm64
Hyperledger-TWGC/ccs-gm pull request #32
Opened 2022-02-12 13:20 UTC by triplewz

[issue#30]( #30)

2022-02-12 13:30 UTC, SamYuan1990 commented
@triplewz , 能否在ci中加上mac的测试？参考 https://github.com/Hyperledger-TWGC/tape/blob/master/azure-pipelines.yml#L30

2022-02-13 02:35 UTC, SamYuan1990 requested changes
<img width="928" alt="image" src="https://user-images.githubusercontent.com/7820992/153735835-4da2419f-9730-49f4-9fa8-1257678aadcb.png">
CI is breaking. please fix.

2022-02-13 03:09 UTC, triplewz commented
应该不需要mac的测试，只需要arm64的测试，我尝试修改下

2022-02-18 08:31 UTC, triplewz commented
@SamYuan1990 ，我看了下，azurepipeline似乎不支持配置架构信息，不支持arm或amd？目前看只有travisci是可以支持的，已经配置了

2022-02-18 12:21 UTC, SamYuan1990 commented
> @SamYuan1990 ，我看了下，azurepipeline似乎不支持配置架构信息，不支持arm或amd？目前看只有travisci是可以支持的，已经配置了

<img width="849" alt="image" src="https://user-images.githubusercontent.com/7820992/154681854-c8ca222f-a867-4614-9232-3ffa241e9b93.png">

但是ci貌似没跑啊。我的想法是既然我们发现问题是通过mac发现的，那么能不能在azp上通过mac来重现或者保证不再次出现这个问题？

2022-02-18 15:21 UTC, SamYuan1990 commented
或者我们试试看`goarch`?
```go build with goarch?```

2022-02-20 13:29 UTC, davidkhala commented
@SamYuan1990 应该是我们Travis CI在我们TWGC组织的问题，我建议先合并了之后再试着手动触发吧

2022-02-20 13:38 UTC, davidkhala commented
> > @SamYuan1990 ，我看了下，azurepipeline似乎不支持配置架构信息，不支持arm或amd？目前看只有travisci是可以支持的，已经配置了
> 
> <img alt="image" width="849" src="https://user-images.githubusercontent.com/7820992/154681854-c8ca222f-a867-4614-9232-3ffa241e9b93.png">
> 
> 但是ci貌似没跑啊。我的想法是既然我们发现问题是通过mac发现的，那么能不能在azp上通过mac来重现或者保证不再次出现这个问题？

另外azp的mac不是m1架构的，所以也没法模拟

2022-02-20 13:42 UTC, davidkhala commented
同时也由于TravisCI政策改变原因，我打算清理了这里的travis设置了

2022-02-20 13:48 UTC, merged

2022-02-20 13:58 UTC, SamYuan1990 commented
ok，那我们放后边做吧

2022-03-07 04:31 UTC, davidkhala commented
@triplewz self-host runner配置成功了，CI也过了，见
https://github.com/Hyperledger-TWGC/ccs-gm/runs/5443055298?check_suite_focus=true